name: simple_android_notification
description: "simple android notification manager"
version: 0.0.2
repository: https://github.com/jhssong/simple_android_notification

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jhssong.simple_android_notification
        pluginClass: SimpleAndroidNotificationPlugin
